### ISSUE TITLE
Relevamiento de campo

### ISSUE THREAD

**Issue by thessaly** [rlyehlab/ciencia-comunitaria#1]
Generar documento con información a buscar a campo

**Comment by thessaly** [comment]
# Datos a relevar

## Infraestructura
- Conectividad
- Electricidad
- Clima
- Acceso
- Movimiento
- Condiciones del lugar de instalación
- Formación de la gente involucrada
- Necesidades de la gente

**Comment by violenti** [comment]
agrego a juli

**Comment by thessaly** [comment]
Done /recursos/relevamientocampo.md
