### ISSUE TITLE
Subir mapa del área con puntos de referencia

### ISSUE THREAD

**Issue by thessaly** [rlyehlab/ciencia-comunitaria#8]

**Comment by Danieldaza** [comment]
https://www.openstreetmap.org/?mlat=-34.5378&mlon=-58.5981#map=14/-34.5378/-58.5981

**Comment by Danieldaza** [comment]
https://github.com/rlyehlab/ciencia-comunitaria/blob/master/ETER/recursos/pdf.pdf
